/* Copyright (c) 2011-2015, 2018-2021 The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials provided
 *       with the distribution.
 *     * Neither the name of The Linux Foundation, nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/*
 * Changes from Qualcomm Technologies, Inc. are provided under the following license:
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
*/

#include <loc_api_v02_log.h>
#include <location_service_v02.h>

DECLARE_TBL(loc_v02_event_name) =
{
   {QMI_LOC_GET_SUPPORTED_MSGS_REQ_V02, "GET_SUPPORTED_MSGS"},
   {QMI_LOC_REG_EVENTS_REQ_V02, "REG_EVENTS"},
   {QMI_LOC_START_REQ_V02, "START_POS_SESSION"},
   {QMI_LOC_STOP_REQ_V02, "STOP_POS_SESSION"},
   {QMI_LOC_EVENT_POSITION_REPORT_IND_V02, "EVENT_POSITION_REPORT"},
   {QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02, "EVENT_GNSS_SV_INFO"},
   {QMI_LOC_EVENT_NMEA_IND_V02, "EVENT_NMEA"},
   {QMI_LOC_EVENT_NI_NOTIFY_VERIFY_REQ_IND_V02, "EVENT_NI_NOTIFY_VERIFY_REQ"},
   {QMI_LOC_EVENT_INJECT_TIME_REQ_IND_V02, "EVENT_INJECT_TIME_REQ"},
   {QMI_LOC_EVENT_INJECT_PREDICTED_ORBITS_REQ_IND_V02, "EVENT_INJECT_PREDICTED_ORBITS_REQ"},
   {QMI_LOC_EVENT_ENGINE_STATE_IND_V02, "EVENT_ENGINE_STATE"},
   {QMI_LOC_EVENT_WIFI_REQ_IND_V02, "EVENT_WIFI_REQ"},
   {QMI_LOC_EVENT_SENSOR_STREAMING_READY_STATUS_IND_V02, "EVENT_SENSOR_STREAMING_READY_STATUS"},
   {QMI_LOC_EVENT_TIME_SYNC_REQ_IND_V02, "EVENT_TIME_SYNC_REQ"},
   {QMI_LOC_EVENT_SET_SPI_STREAMING_REPORT_IND_V02, "EVENT_SET_SPI_STREAMING_REPORT"},
   {QMI_LOC_EVENT_LOCATION_SERVER_CONNECTION_REQ_IND_V02, "EVENT_LOCATION_SERVER_CONNECTION_REQ"},
   {QMI_LOC_NI_USER_RESPONSE_REQ_V02, "NI_USER_RESPONSE"},
   {QMI_LOC_GET_PREDICTED_ORBITS_DATA_SOURCE_REQ_V02, "GET_PREDICTED_ORBITS_DATA_SOURCE"},
   {QMI_LOC_INJECT_UTC_TIME_REQ_V02, "INJECT_UTC_TIME"},
   {QMI_LOC_INJECT_POSITION_REQ_V02, "INJECT_POSITION"},
   {QMI_LOC_SET_ENGINE_LOCK_REQ_V02, "SET_ENGINE_LOCK"},
   {QMI_LOC_GET_ENGINE_LOCK_REQ_V02, "GET_ENGINE_LOCK"},
   {QMI_LOC_SET_NMEA_TYPES_REQ_V02, "SET_NMEA_TYPES"},
   {QMI_LOC_GET_NMEA_TYPES_REQ_V02, "GET_NMEA_TYPES"},
   {QMI_LOC_REGISTER_MASTER_CLIENT_REQ_V02, "REGISTER_MASTER_CLIENT"},
   {QMI_LOC_SET_SERVER_REQ_V02, "SET_SERVER"},
   {QMI_LOC_SET_XTRA_T_SESSION_CONTROL_REQ_V02, "SET_XTRA_T_SESSION_CONTROL"},
   {QMI_LOC_NOTIFY_WIFI_STATUS_REQ_V02, "NOTIFY_WIFI_STATUS"},
   {QMI_LOC_SET_OPERATION_MODE_REQ_V02, "SET_OPERATION_MODE"},
   {QMI_LOC_SET_SPI_STATUS_REQ_V02, "SET_SPI_STATUS"},
   {QMI_LOC_INJECT_SENSOR_DATA_REQ_V02, "INJECT_SENSOR_DATA"},
   {QMI_LOC_INJECT_TIME_SYNC_DATA_REQ_V02, "INJECT_TIME_SYNC_DATA"},
   {QMI_LOC_SET_EXTERNAL_POWER_CONFIG_REQ_V02, "SET_EXTERNAL_POWER_CONFIG"},
   {QMI_LOC_INFORM_LOCATION_SERVER_CONN_STATUS_REQ_V02, "INFORM_LOCATION_SERVER_CONN_STATUS"},
   {QMI_LOC_SET_PROTOCOL_CONFIG_PARAMETERS_REQ_V02, "SET_PROTOCOL_CONFIG_PARAMETERS"},
   {QMI_LOC_SET_SENSOR_PROPERTIES_REQ_V02, "SET_SENSOR_PROPERTIES"},
   {QMI_LOC_SET_SENSOR_PERFORMANCE_CONTROL_CONFIGURATION_REQ_V02,
       "SET_SENSOR_PERFORMANCE_CONTROL_CONFIGURATION"},
   {QMI_LOC_INJECT_SUPL_CERTIFICATE_REQ_V02, "INJECT_SUPL_CERTIFICATE_REQ"},
   {QMI_LOC_EVENT_GEOFENCE_GEN_ALERT_IND_V02, "EVENT_GEOFENCE_GEN_ALERT"},
   {QMI_LOC_EVENT_GEOFENCE_BREACH_NOTIFICATION_IND_V02, "EVENT_GEOFENCE_BREACH_NOTIFICATION"},
   {QMI_LOC_ADD_CIRCULAR_GEOFENCE_REQ_V02, "ADD_CIRCULAR_GEOFENCE"},
   {QMI_LOC_DELETE_GEOFENCE_REQ_V02, "DELETE_GEOFENCE"},
   {QMI_LOC_EDIT_GEOFENCE_REQ_V02, "EDIT_GEOFENCE"},
   {QMI_LOC_GET_BEST_AVAILABLE_POSITION_REQ_V02, "GET_BEST_AVAILABLE_POSITION"},
   {QMI_LOC_GET_AVAILABLE_WWAN_POSITION_REQ_V02, "GET_AVAILABLE_WWAN_POSITION"},
   {QMI_LOC_INJECT_MOTION_DATA_REQ_V02, "INJECT_MOTION_DATA"},
   {QMI_LOC_EVENT_PEDOMETER_CONTROL_IND_V02, "EVENT_PEDOMETER_CONTROL"},
   {QMI_LOC_EVENT_MOTION_DATA_CONTROL_IND_V02, "EVENT_MOTION_DATA_CONTROL"},
   {QMI_LOC_PEDOMETER_REPORT_REQ_V02, "PEDOMETER_REPORT"},
   {QMI_LOC_GET_BATCH_SIZE_REQ_V02, "GET_BATCH_SIZE"},
   {QMI_LOC_START_BATCHING_REQ_V02, "START_BATCHING"},
   {QMI_LOC_EVENT_BATCH_FULL_NOTIFICATION_IND_V02, "EVENT_BATCH_FULL_NOTIFICATION"},
   {QMI_LOC_READ_FROM_BATCH_REQ_V02, "READ_FROM_BATCH"},
   {QMI_LOC_STOP_BATCHING_REQ_V02, "STOP_BATCHING"},
   {QMI_LOC_RELEASE_BATCH_REQ_V02, "RELEASE_BATCH"},
   {QMI_LOC_EVENT_INJECT_WIFI_AP_DATA_REQ_IND_V02, "EVENT_INJECT_WIFI_AP_DATA_REQ"},
   {QMI_LOC_INJECT_WIFI_AP_DATA_REQ_V02, "INJECT_WIFI_AP_DATA"},
   {QMI_LOC_NOTIFY_WIFI_ATTACHMENT_STATUS_REQ_V02, "NOTIFY_WIFI_ATTACHMENT_STATUS"},
   {QMI_LOC_NOTIFY_WIFI_ENABLED_STATUS_REQ_V02, "NOTIFY_WIFI_ENABLED_STATUS"},
   {QMI_LOC_EVENT_GEOFENCE_BATCHED_BREACH_NOTIFICATION_IND_V02,
       "EVENT_GEOFENCE_BATCHED_BREACH_NOTIFICATION"},
   {QMI_LOC_SET_PREMIUM_SERVICES_CONFIG_REQ_V02, "SET_PREMIUM_SERVICES_CONFIG"},
   {QMI_LOC_SET_XTRA_VERSION_CHECK_REQ_V02, "SET_XTRA_VERSION_CHECK"},
   {QMI_LOC_EVENT_GNSS_MEASUREMENT_REPORT_IND_V02, "EVENT_GNSS_MEASUREMENT_REPORT"},
   {QMI_LOC_EVENT_SV_POLYNOMIAL_REPORT_IND_V02, "EVENT_SV_POLYNOMIAL_REPORT"},
   {QMI_LOC_SET_GNSS_CONSTELL_REPORT_CONFIG_V02, "SET_GNSS_CONSTELL_REPORT_CONFIG"},
   {QMI_LOC_EVENT_GEOFENCE_BATCHED_DWELL_NOTIFICATION_IND_V02,
       "EVENT_GEOFENCE_BATCHED_DWELL_NOTIFICATION"},
   {QMI_LOC_EVENT_GET_TIME_ZONE_INFO_IND_V02, "EVENT_GET_TIME_ZONE_INFO"},
   {QMI_LOC_INJECT_TIME_ZONE_INFO_REQ_V02, "INJECT_TIME_ZONE_INFO"},
   {QMI_LOC_EVENT_BATCHING_STATUS_IND_V02, "EVENT_BATCHING_STATUS"},
   {QMI_LOC_DELETE_GNSS_SERVICE_DATA_REQ_V02, "DELETE_GNSS_SERVICE_DATA"},
   {QMI_LOC_INJECT_XTRA_DATA_REQ_V02, "INJECT_XTRA_DATA"},
   {QMI_LOC_INJECT_XTRA_PCID_REQ_V02, "INJECT_XTRA_PCID"},
   {QMI_LOC_GET_SUPPORTED_FEATURE_REQ_V02, "GET_SUPPORTED_FEATURE"},
   {QMI_LOC_QUERY_XTRA_INFO_REQ_V02, "QUERY_XTRA_INFO"},
   {QMI_LOC_SET_BLACKLIST_SV_REQ_V02, "SET_BLACKLIST_SV"},
   {QMI_LOC_GET_BLACKLIST_SV_REQ_V02, "GET_BLACKLIST_SV"},
   {QMI_LOC_SET_CONSTELLATION_CONTROL_REQ_V02, "SET_CONSTELLATION_CONTROL"},
   {QMI_LOC_EVENT_UNPROPAGATED_POSITION_REPORT_IND_V02, "EVENT_UNPROPAGATED_POSITION_REPORT_IND"},
   {QMI_LOC_SET_CONSTRAINED_TUNC_MODE_REQ_V02, "SET_CONSTRAINED_TUNC_MODE"},
   {QMI_LOC_ENABLE_POSITION_ASSISTED_CLOCK_EST_REQ_V02, "ENABLE_POSITION_ASSISTED_CLOCK_EST"},
   {QMI_LOC_QUERY_GNSS_ENERGY_CONSUMED_REQ_V02, "QUERY_GNSS_ENERGY_CONSUMED"},
   {QMI_LOC_EVENT_REPORT_IND_V02, "EVENT_REPORT"},
   {QMI_LOC_EVENT_GPS_EPHEMERIS_REPORT_IND_V02, "EVENT_GPS_EPHEMERIS_REPORT"},
   {QMI_LOC_EVENT_GLONASS_EPHEMERIS_REPORT_IND_V02, "EVENT_GLONASS_EPHEMERIS_REPORT"},
   {QMI_LOC_EVENT_BDS_EPHEMERIS_REPORT_IND_V02, "EVENT_BDS_EPHEMERIS_REPORT"},
   {QMI_LOC_EVENT_GALILEO_EPHEMERIS_REPORT_IND_V02, "EVENT_GALILEO_EPHEMERIS_REPORT"},
   {QMI_LOC_EVENT_QZSS_EPHEMERIS_REPORT_IND_V02, "EVENT_QZSS_EPHEMERIS_REPORT_IND"},
   {QMI_LOC_SYSTEM_INFO_REQ_V02, "SYSTEM_INFO"},
   {QMI_LOC_EVENT_UNPROPAGATED_POSITION_REPORT_IND_V02, "EVENT_UNPROPAGATED_POSITION_REPORT"},
   {QMI_LOC_LOCATION_REQUEST_NOTIFICATION_IND_V02, "LOCATION_REQUEST_NOTIFICATION_IND"},
   {QMI_LOC_INJECT_PLATFORM_POWER_STATE_REQ_V02, "INJECT_PLATFORM_POWER_STATE"},
   {QMI_LOC_SET_ROBUST_LOCATION_CONFIG_REQ_V02, "SET_ROBUST_LOCATION_CONFIG"},
   {QMI_LOC_GET_ROBUST_LOCATION_CONFIG_REQ_V02, "GET_ROBUST_LOCATION_CONFIG"},
   {QMI_LOC_SET_MIN_GPS_WEEK_NUMBER_REQ_V02, "SET_MIN_GPS_WEEK_NUMBER"},
   {QMI_LOC_GET_MIN_GPS_WEEK_NUMBER_REQ_V02, "GET_MIN_GPS_WEEK_NUMBER"},
   {QMI_LOC_EVENT_QUERY_XTRA_INFO_REQ_IND_V02, "EVENT_QUERY_XTRA_INFO_REQ"},
   {QMI_LOC_SET_PARAMETER_REQ_V02, "SET_PARAMETER"},
   {QMI_LOC_GET_PARAMETER_REQ_V02, "GET_PARAMETER"},
   {QMI_LOC_SET_MULTIBAND_CONFIG_REQ_V02, "SET_MULTIBAND_CONFIG"},
   {QMI_LOC_GET_MULTIBAND_CONFIG_REQ_V02, "GET_MULTIBAND_CONFIG"},
   {QMI_LOC_INJECT_LOCATION_CIVIC_ADDRESS_REQ_V02, "INJECT_LOCATION_CIVIC_ADDRESS"},
   {QMI_LOC_EVENT_PLATFORM_POWER_STATE_CHANGED_IND_V02, "EVENT_PLATFORM_POWER_STATE_CHANGED"},
   {QMI_LOC_ENGINE_DEBUG_DATA_IND_V02, "ENGINE_DEBUG_DATA"},
   {QMI_LOC_DC_REPORT_IND_V02, "DC_REPORT"},
   {QMI_LOC_EVENT_ENGINE_LOCK_STATE_IND_V02, "EVENT_ENGINE_LOCK_STATE"},
   {QMI_LOC_SET_TRIBAND_STATE_REQ_V02, "SET_TRIBAND_STATE"},
   {QMI_LOC_SET_SDK_FEATURE_CONFIG_REQ_V02, "SET_SDK_FEATURE_CONFIG"},
   {QMI_LOC_GNSS_BANDS_SUPPORTED_IND_V02, "GNSS_BANDS_SUPPORTED_IND"},
   {QMI_LOC_OSNMA_PUBLIC_KEY_MERKLE_TREE_REQ_V02, "OSNMA_PUBLIC_KEY_MERKLE_TREE"},
   {QMI_LOC_SET_OSNMA_STATE_REQ_V02, "SET_OSNMA_STATE"},
   {QMI_LOC_SET_NTN_STATUS_REQ_V02, "SET_NTN_STATUS"},
   {QMI_LOC_GET_NTN_STATUS_REQ_V02, "GET_NTN_STATUS"},
   {QMI_LOC_SET_PRECISE_SESSION_CONFIG_REQ_V02, "SET_PRECISE_SESSION_CONFIG"},
   // FDCL
   {QMI_LOC_EVENT_FDCL_SERVICE_REQ_IND_V02, "EVENT_FDCL_SERVICE_REQ"},
   {QMI_LOC_GET_FDCL_BS_LIST_REQ_V02, "GET_FDCL_BS_LIST"},
   {QMI_LOC_INJECT_FDCL_DATA_REQ_V02, "INJECT_FDCL_DATA"},
   {QMI_LOC_EVENT_BS_OBS_DATA_SERVICE_REQ_IND_V02, "EVENT_BS_OBS_DATA_SERVICE_REQ"},
   {QMI_LOC_GET_BS_OBS_DATA_REQ_V02, "GET_BS_OBS_DATA"},
   // Please note, as req, resp, ind has same enum, only one entry need to be added in above table
};

const char* loc_get_v02_event_name(uint32_t event)
{
    return loc_get_name_from_val(loc_v02_event_name_tbl, (int64_t) event);
}

DECLARE_TBL(loc_v02_client_status_name) =
{
    NAME_VAL(eLOC_CLIENT_SUCCESS),
    NAME_VAL(eLOC_CLIENT_FAILURE_GENERAL),
    NAME_VAL(eLOC_CLIENT_FAILURE_UNSUPPORTED),
    NAME_VAL(eLOC_CLIENT_FAILURE_INVALID_PARAMETER),
    NAME_VAL(eLOC_CLIENT_FAILURE_ENGINE_BUSY),
    NAME_VAL(eLOC_CLIENT_FAILURE_PHONE_OFFLINE),
    NAME_VAL(eLOC_CLIENT_FAILURE_TIMEOUT),
    NAME_VAL(eLOC_CLIENT_FAILURE_SERVICE_NOT_PRESENT),
    NAME_VAL(eLOC_CLIENT_FAILURE_SERVICE_VERSION_UNSUPPORTED),
    NAME_VAL(eLOC_CLIENT_FAILURE_CLIENT_VERSION_UNSUPPORTED),
    NAME_VAL(eLOC_CLIENT_FAILURE_INVALID_HANDLE),
    NAME_VAL(eLOC_CLIENT_FAILURE_INTERNAL),
    NAME_VAL(eLOC_CLIENT_FAILURE_NOT_INITIALIZED),
    NAME_VAL(eLOC_CLIENT_FAILURE_NOT_ENOUGH_MEMORY),
    NAME_VAL(eLOC_CLIENT_FAILURE_INVALID_MESSAGE_ID),
};

const char* loc_get_v02_client_status_name(locClientStatusEnumType status)
{
    return loc_get_name_from_val(loc_v02_client_status_name_tbl, (int64_t) status);
}


DECLARE_TBL(loc_v02_qmi_status_name) =
{
    NAME_VAL(eQMI_LOC_SUCCESS_V02),
    NAME_VAL(eQMI_LOC_GENERAL_FAILURE_V02),
    NAME_VAL(eQMI_LOC_UNSUPPORTED_V02),
    NAME_VAL(eQMI_LOC_INVALID_PARAMETER_V02),
    NAME_VAL(eQMI_LOC_ENGINE_BUSY_V02),
    NAME_VAL(eQMI_LOC_PHONE_OFFLINE_V02),
    NAME_VAL(eQMI_LOC_TIMEOUT_V02),
    NAME_VAL(eQMI_LOC_CONFIG_NOT_SUPPORTED_V02),
    NAME_VAL(eQMI_LOC_INSUFFICIENT_MEMORY_V02),
    NAME_VAL(eQMI_LOC_MAX_GEOFENCE_PROGRAMMED_V02),
    NAME_VAL(eQMI_LOC_XTRA_VERSION_CHECK_FAILURE_V02),
    NAME_VAL(eQMI_LOC_GNSS_DISABLED_V02),
};

const char* loc_get_v02_qmi_status_name(qmiLocStatusEnumT_v02 status)
{
    return loc_get_name_from_val(loc_v02_qmi_status_name_tbl, (int64_t) status);
}


DECLARE_TBL(loc_v02_qmi_reg_mk_status_name) =
{
    NAME_VAL(eQMI_LOC_REGISTER_MASTER_CLIENT_SUCCESS_V02),
    NAME_VAL(eQMI_LOC_REGISTER_MASTER_CLIENT_INVALID_KEY_V02),
    NAME_VAL(eQMI_LOC_REGISTER_MASTER_CLIENT_ALREADY_HAVE_MASTER_CLIENT_V02),
    NAME_VAL(eQMI_LOC_REGISTER_MASTER_CLIENT_INTERNAL_FAILURE_V02),
};

const char* loc_get_v02_qmi_reg_mk_status_name(qmiLocRegisterMasterClientStatusEnumT_v02 status)
{
    return loc_get_name_from_val(loc_v02_qmi_reg_mk_status_name_tbl, (int64_t)status);
}
